// Reads every node file under graph/nodes/, validates the graph, and generates
// graph/index.md (the agent's system prompt) and docs/graph-data.json (the
// website's visualization data). Run with: bun scripts/sync-graph.mjs
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const nodesDir = join(root, "graph", "nodes");

// Order also defines how blocks are sorted in the index: the project first,
// then what it rests on, how it is built, and where it breaks.
const TYPES = ["Project", "Concept", "Component", "Step", "Limitation"];

function fail(file, line, message) {
  console.error(`graph/nodes/${file}:${line} ${message}`);
  process.exit(1);
}

// The frontmatter schema is constrained enough for a hand-written parser:
// plain scalars for id and type, a JSON style array for notes, and one
// flow-mapping line per edge.
function parseNode(file) {
  const lines = readFileSync(join(nodesDir, file), "utf8").split("\n");
  if (lines[0] !== "---") fail(file, 1, "frontmatter must start with ---");

  const node = { file, id: null, type: null, notes: [], edges: [] };
  let closed = false;

  for (let i = 1; i < lines.length; i++) {
    const line = lines[i];
    const at = i + 1;
    if (line === "---") { closed = true; break; }
    if (line.trim() === "") continue;

    if (line.startsWith("id:")) {
      node.id = line.slice(3).trim();
    } else if (line.startsWith("type:")) {
      node.type = line.slice(5).trim();
    } else if (line.startsWith("notes:")) {
      try {
        node.notes = JSON.parse(line.slice(6).trim());
      } catch {
        fail(file, at, "notes must be an array of double-quoted strings");
      }
    } else if (line.startsWith("edges:")) {
      const rest = line.slice(6).trim();
      if (rest !== "" && rest !== "[]") fail(file, at, "edges must be [] or a list of - {rel: ..., target: ...} lines");
    } else {
      const edge = line.match(/^\s*-\s*\{\s*rel:\s*([^,}]+?)\s*,\s*target:\s*([^,}]+?)\s*\}\s*$/);
      if (!edge) fail(file, at, `unrecognized frontmatter line: ${line.trim()}`);
      node.edges.push({ rel: edge[1], target: edge[2], line: at });
    }
  }

  if (!closed) fail(file, lines.length, "frontmatter never closed with ---");
  if (!node.id) fail(file, 1, "missing id");
  if (node.id !== file.replace(/\.md$/, "")) fail(file, 1, `id "${node.id}" does not match the filename`);
  if (!TYPES.includes(node.type)) fail(file, 1, `type must be one of: ${TYPES.join(", ")}`);
  return node;
}

const files = readdirSync(nodesDir).filter((f) => f.endsWith(".md")).sort();
const nodes = files.map(parseNode);
const ids = new Set(nodes.map((n) => n.id));

for (const node of nodes) {
  for (const edge of node.edges) {
    if (!ids.has(edge.target)) fail(node.file, edge.line, `edge target "${edge.target}" does not exist`);
  }
}

nodes.sort((a, b) => TYPES.indexOf(a.type) - TYPES.indexOf(b.type) || a.id.localeCompare(b.id));

const index = [
  "<!-- generated by scripts/sync-graph.mjs, do not edit by hand -->",
  ...nodes.map((n) =>
    [
      `## ${n.id}`,
      `type: ${n.type}`,
      `notes: ${n.notes.join(", ")}`,
      `edges: ${n.edges.length ? n.edges.map((e) => `${e.rel} -> ${e.target}`).join(", ") : "none"}`,
      `path: graph/nodes/${n.id}.md`,
    ].join("\n"),
  ),
].join("\n\n") + "\n";

const graphData = JSON.stringify(
  {
    nodes: nodes.map((n) => ({ id: n.id, type: n.type, notes: n.notes })),
    edges: nodes.flatMap((n) => n.edges.map((e) => ({ source: n.id, target: e.target, rel: e.rel }))),
  },
  null,
  2,
) + "\n";

writeFileSync(join(root, "graph", "index.md"), index);
writeFileSync(join(root, "docs", "graph-data.json"), graphData);

console.log(`synced ${nodes.length} nodes and ${nodes.reduce((sum, n) => sum + n.edges.length, 0)} edges into graph/index.md and docs/graph-data.json`);
